import { useCallback, useContext, useEffect, useState } from 'react'

import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import { SocketContext } from '../utils/socketUtils'

const Home: NextPage = () => {
  const socket = useContext(SocketContext)

  const [connected, setConnected] = useState(false)

  const [message, setMessage] = useState<string>('')
  const [chat, setChat] = useState<string[]>([])

  const updateChat = useCallback(
    (message: string) => {
      console.log(message)
      setChat(chat.concat([message]))
    },
    [chat]
  )

  const submitText = () => {
    console.log('emit', message)
    socket.emit('msgToServer', message)
  }

  useEffect(() => {
    socket.on('msgToClient', updateChat)
    return () => {
      socket.off('msgToClient', updateChat)
    }
  }, [updateChat])

  return (
    <div className={styles.container}>
      <Head>
        <title>Find My Mines</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Beam Corp</h1>

        {chat.map((value, index) => (
          <div key={`${index}`}>{value}</div>
        ))}

        <input onChange={(e) => setMessage(e.target.value)} />
        <button onClick={submitText}> Submit </button>
      </main>
    </div>
  )
}

export default Home
